version: '3.8'

services:
  db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: blog  
    volumes:
      - db_data:/data/db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - db
    command: >
      sh -c "npx prisma generate &&
             npm run dev"

volumes:
  db_data:
